### ISSUE TITLE
Dark theme colors

### ISSUE THREAD

**Issue by Nikodemsky** [webextensions/live-css-editor#59]
There's few problems with colors on dark theme
![color1](https://user-images.githubusercontent.com/14090596/96942789-5e256d00-14d6-11eb-9005-7bfac183ff49.png)

1. Comments needs to be a bit brighter, you can almost not see them at all. Comments works as reference in most cases - those needs to be noticable enough.
2. Scrollbar color - it's too dark. sometimes i need to squeeze my eyes just to find the thingy :) 
3. Unfinished/wrong code color. It's also too dark, many times i don't even know that typo i'm making because of this.

btw. is this some kind of particular set of colors or is it all-custom?

**Comment by webextensions** [comment]
@Nikodemsky 

We use CodeMirror themes with minor customizations for scrollbar and resizer. You may have a look at the themes here: https://codemirror.net/demo/theme.html . We use "ambiance" theme from this list. Please note that the example at that URL uses JavaScript code, so you may not be able to test all cases involving syntax highlighting for CSS/Less/Sass.

1. Kindly suggest any other better dark theme from this list which you feel is good enough in general while highlighting the code comments in a better manner.

2. For scrollbar colors, we use the following CSS. Can you copy-paste them into the live editor, play around with these styles and recommend any combination you like better?
```css
#MagiCSS-bookmarklet .cm-s-ambiance ::-webkit-scrollbar {
    background: rgba(0, 0, 0, 0.9);
}
#MagiCSS-bookmarklet .cm-s-ambiance ::-webkit-scrollbar-thumb {
    background: rgba(71, 71, 71, 0.6);
    box-shadow: inset 0 0 6px rgb(0, 0, 0);
}
```

3. Same as point 1.

**Note:**
For point 1 and point 3, our preference would be to change the theme itself in such a case. Reason being that if theme doesn't work expectedly well in some cases, then there might be more undiscovered cases where things may go wrong later. Of course, the above mentioned points are just preferences and not hard rules. If these two are the only cases where things go wrong, we may fix the CSS specifically for these cases.

**Comment by Nikodemsky** [comment]
1. Monokai, but it might require a bit of tweaking. I never liked native codemirror themes :\  The perfect would be sumblime variant for monokai:
https://github.com/gerardroche/sublime-monokai-free
- but that would require converting styles i presume.

2. Something like this maybe:
`#MagiCSS-bookmarklet .cm-s-ambiance ::-webkit-scrollbar {
    background: rgba(68,68,68,0.9);
}
#MagiCSS-bookmarklet .cm-s-ambiance ::-webkit-scrollbar-thumb {
    background: rgba(128,127,127,0.6);
    box-shadow: inset 0 0 6px rgb(92,91,91);
}`

**Comment by webextensions** [comment]
@Nikodemsky 
Updated the scrollbar colors with the change: https://github.com/webextensions/live-css-editor/commit/ea904a25d8312e251640e120fb264ef129133664

Regarding theme, implementing natively available ones would be easier to do and more maintainable in long term.
If you are unable to find a ntive one which is good enough, then probably fixing on case-by-case basis would be easier and faster.

If you would prefer to play around with the styling, here is the default one for reference:
```css
.cm-s-ambiance .cm-comment {
    color: rgb(85, 85, 85);
}

.cm-s-ambiance .cm-error {
    color: rgb(175, 32, 24);
}
```
